### ISSUE TITLE
Issues with CrystalConv or other MessagePassing layers with edge features

### ISSUE THREAD

**Issue by gastoneb** [danielegrattarola/spektral#116]
Hi, I am trying to build a node regression model that combines node features & edge features. At a glance, CrystalConv (MessagePassing) seemed like the best/only tool. There isn't a CrystalConv example or test though, and the only MessagePassing example I could find (tud_disjoint) is written in the imperative style and doesn't include edge features. 

I had some issues building a CrystalConv layer model using my own dataset, but to reproduce the issue I built an example using the cora dataset. 

## Issues
* There's a ValueError saying that the number of nodes and number of edges should match up?
* I'm not totally certain that the message function for CrystalConv is complete. Seems to me that it should be calling E_ij=get_ij(E) or something like that. I'm probably wrong but it looks like it's trying to concatenate X_i, X_j, and the entire E tensor?

Before I spend too much time on this I wanted to ask whether the CrystalConv and MessagePassing implementations are complete and tested, for layers that include edge features. 

## System Info
* OS: Ubuntu 20.04 (Running with WSL 2)
* CUDA 10.1
* cudnn 7.6
* Python 3.8.3
* tensorflow 2.2.0 (conda)
* spektral 0.6.2 (built locally too and no difference)

## Demo
```
"""
Trying to implement a CrystalConv layer using the citation networks dataset, 
with some dummy edge feature data.
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Input, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

from spektral.datasets import citation
from spektral.layers import CrystalConv

import numpy as np

# Load data
dataset = 'cora'
A, X, y, train_mask, val_mask, test_mask = citation.load_data(dataset)
X = X[:,0:5] # Model doesn't compile with multiple node features?
X = X.todense().astype('float32')
X = tf.convert_to_tensor(X)

# Build dummy edge feature data
n_edges = np.sum(A)
E = np.ones((n_edges,1)).astype('float32')
E = tf.convert_to_tensor(E)

# Make dummy 1-class y
y = y[:,0].reshape((y.shape[0],1))

# Parameters
channels = 16           # Number of channels in the first layer
N = X.shape[0]          # Number of nodes in the graph
F = X.shape[1]          # Original size of node features
S = E.shape[1]          # Number of edge features
n_edges = E.shape[0]    # Number of edges
n_classes = y.shape[1]  # Number of classes
dropout = 0.5           # Dropout rate for the features
l2_reg = 5e-4 / 2       # L2 regularization rate
learning_rate = 1e-2    # Learning rate
epochs = 200            # Number of training epochs
es_patience = 10        # Patience for early stopping

print(N,F,S,n_edges,n_classes)

# Model definition
X_in = Input(shape=(F, ))
A_in = Input(shape=(N, ), sparse=True)
E_in = Input(shape=(S, ))

crystal_conv_1 = CrystalConv(n_classes,
                         activation='relu',
                         kernel_regularizer=l2(l2_reg),
                         use_bias=False)([X_in, A_in, E_in])

# Build model
model = Model(inputs=[X_in, A_in, E_in], outputs=crystal_conv_1)
optimizer = Adam(lr=learning_rate)
model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              weighted_metrics=['acc'])
model.summary()

# Train model
validation_data = ([X, A, E], y, val_mask)
model.fit([X, A, E],
          y,
          sample_weight=train_mask,
          epochs=epochs,
          batch_size=N,
          validation_data=validation_data,
          shuffle=False  # Shuffling data means shuffling the whole graph
)
```

Result:
```
Loading cora dataset
Pre-processing node features
2708 1 1 10556 1
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            [(None, 1)]          0
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 2708)]       0
__________________________________________________________________________________________________
input_3 (InputLayer)            [(None, 1)]          0
__________________________________________________________________________________________________
crystal_conv (CrystalConv)      (None, 1)            8           input_1[0][0]
                                                                 input_2[0][0]
                                                                 input_3[0][0]
==================================================================================================
Total params: 8
Trainable params: 8
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "test_crystal.py", line 81, in <module>
    model.fit([X, A, E],
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 802, in fit
    data_handler = data_adapter.DataHandler(
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1100, in __init__
    self._adapter = adapter_cls(
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 573, in __init__
    dataset = dataset_ops.DatasetV2.from_tensor_slices(inputs)
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 640, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2867, in __init__
    batch_dim.assert_is_compatible_with(tensor_shape.Dimension(
  File "/home/gastoneb/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py", line 275, in assert_is_compatible_with
    raise ValueError("Dimensions %s and %s are not compatible" %
ValueError: Dimensions 2708 and 10556 are not compatible
```

**Comment by danielegrattarola** [comment]
Hi, 

The example you should be looking at is [this one](https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/qm9_disjoint.py#L101-L106), just remove the [GlobalSumPool layer](https://github.com/danielegrattarola/spektral/blob/ecfe36ee552ee4c9828bc521a0a796b84ca31ce3/examples/graph_prediction/qm9_disjoint.py#L67).

Unfortunately, you can't use Keras' `model.fit()` in this case. You can keep the custom training loop in the example above, you just need to change [these lines](https://github.com/danielegrattarola/spektral/blob/ecfe36ee552ee4c9828bc521a0a796b84ca31ce3/examples/graph_prediction/qm9_disjoint.py#L101-L106) because you don't need batching if you're doing node classification in single mode (i.e., with only one graph).

>Seems to me that it should be calling E_ij=get_ij(E) or something like that. I'm probably wrong but it looks like it's trying to concatenate X_i, X_j, and the entire E tensor?

It is. If you want to read it in math terms, have a look [here](https://graphneural.network/layers/convolution/#crystalconv).
X_i, and X_j are tensors of shape (n_edges, F), while E has shape (n_edges, S), so the concatenation makes sense. 

Cheers

**Comment by gastoneb** [comment]
Thanks for the clarification about `model.fit()`. I didn't catch the shape of X_i and X_j, so that makes sense now. I'll see if I can implement the procedure from the QM9 disjoint example. You're right - I won't be using mini-batching.
