### ISSUE TITLE
Node-level classification in Disjoint mode with batch size > 1 or node_level=True: dimensionality of target variable y

### ISSUE THREAD

**Issue by herman-nside** [danielegrattarola/spektral#163]
I have a GNN that works when I specify the loader as:

```Python
loader = spektral.data.loaders.DisjointLoader(dataset, batch_size=1)
```
However, when I increase the batch size, e.g.:

```Python
loader = spektral.data.loaders.DisjointLoader(dataset, batch_size=2)
```

I get:

```python
Traceback (most recent call last):
  File "/Users/hca/PycharmProjects/Switching%20notes/ai/tests/test.py", line 30, in <module>
    model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [26,1] vs. [2,13]
	 [[node gradient_tape/binary_crossentropy/logistic_loss/mul/BroadcastGradientArgs (defined at Users/hca/PycharmProjects/Switching%20notes/ai/tests/test.py:30) ]] [Op:__inference_train_function_3011]

Function call stack:
train_function
```
Here it seems to me that the loader adds an additional dimension to the target variable, but this dimension is not expected in the model itself. I can specify a batch size inside `model.fit()`, and that works if I don't specify a batch size larger than 1 inside `DisjointLoader`, but I am not sure how these interact and whether that is a good idea? Is there something else that I should do when I want to run batches?

Also, regarding node-level classification, when I specify

```python
loader = spektral.data.loaders.DisjointLoader(dataset, node_level=True)
```
I get:
```python
Traceback (most recent call last):
  File "/Users/hca/PycharmProjects/Switching%20notes/ai/tests/test.py", line 30, in <module>
    model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TypeError: `generator` yielded an element of ((TensorSpec(shape=(13, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([13, 13]), tf.int64), TensorSpec(shape=(13,), dtype=tf.int64, name=None)), TensorSpec(shape=(1, 13), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.int64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(None,), dtype=tf.float64, name=None)) was expected.
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 976, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of ((TensorSpec(shape=(13, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([13, 13]), tf.int64), TensorSpec(shape=(13,), dtype=tf.int64, name=None)), TensorSpec(shape=(1, 13), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.int64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(None,), dtype=tf.float64, name=None)) was expected.


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_3015]

Function call stack:
train_function
```
In this case, the shape of `y` is `(1, 13)`, where `(None,)` is expected. However, in the dataset, `y` has the dimensions `(13,)`, which seems to me could have been correct, had `DisjointLoader` not changed that to `(1, 13)`. What am I missing here?

My GNN code is as follows:

```python
import spektral
from dataset_class import GNN_Dataset
from spektral.data.dataset import Dataset
from spektral.layers import GraphSageConv
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model

class SN_GNN(Model):
    def __init__(self):
        super().__init__()
        self.X_in = Input(shape=(13, ),
                     name='X_in')
        self.A_in = Input(shape=(None,),
                     sparse=True,
                     name='A_in')
        self.GraphSage = GraphSageConv(32)
        self.output_layer = Dense(1, activation='softmax')

    def call(self, inputs):
        x, a = inputs[0], inputs[1]
        x = self.GraphSage([x, a])
        out = self.output_layer(x)
        return out
model = SN_GNN()
dataset = GNN_Dataset('/dataset/sn/')
loader = spektral.data.loaders.DisjointLoader(dataset, node_level=True)
model.compile(optimizer='Adam', loss='binary_crossentropy')
model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3)
```

**Comment by danielegrattarola** [comment]
Hi, 

can you try to reshape your node labels `y` so that they have shape `(n_nodes, 1)`? 

Cheers, 
Daniele

**Comment by herman-nside** [comment]
It seems to me that `DisjointLoader` still adds an additional dimension, so that now it expects something of shape `(1, 13, 1)`:

```python
Traceback (most recent call last):
  File "/Users/hca/PycharmProjects/Switching%20notes/ai/tests/test.py", line 29, in <module>
    model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3, batch_size=batch_size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TypeError: `generator` yielded an element of ((TensorSpec(shape=(13, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([13, 13]), tf.int64), TensorSpec(shape=(13,), dtype=tf.int64, name=None)), TensorSpec(shape=(1, 13, 1), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.int64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(None, 1), dtype=tf.float64, name=None)) was expected.
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 976, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of ((TensorSpec(shape=(13, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([13, 13]), tf.int64), TensorSpec(shape=(13,), dtype=tf.int64, name=None)), TensorSpec(shape=(1, 13, 1), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.int64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(None, 1), dtype=tf.float64, name=None)) was expected.


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_3011]

Function call stack:
train_function
```

**Comment by danielegrattarola** [comment]
That is very weird.

Here's a custom example that should be similar to what you are doing.

Create a dataset with 2 graphs, with a different number of nodes and associated with node labels:

```py
from spektral.data import Dataset, Graph

class MyDataset(Dataset):
    def read(self):
        return [
            Graph(x=np.ones((10, 2)), a=np.ones((10, 10)), y=np.ones((10, 1))),
            Graph(x=np.ones((13, 2)), a=np.ones((13, 13)), y=np.ones((13, 1))),
        ]
```

Now create the loader and examine the shape of the batched labels:

```py
from spektral.data import DisjointLoader

dataset = MyDataset()
loader = DisjointLoader(dataset, node_level=True, batch_size=2)
batch = loader.__next__()

assert batch[1].shape == (23, 1)

```

Can you check whether this code works on your machine? 
Thanks

**Comment by herman-nside** [comment]
I get the following:

```python
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/hca/PycharmProjects/Switching%20notes/ai/tests/test.py", line 41, in <module>
    assert batch[1].shape == (23, 1)
AssertionError
```
The shape of `batch[1]` is `(1, 10, 1)`
The versions of the libraries I'm using are:
Spektral version 1.0.3
Tensorflow version 2.4.0

**Comment by herman-nside** [comment]
Indeed, that works on my machine, which seems to mean it is my dataset. I get the following on the two datasets:
```python
MyDataset[1]
x (13, 2)
a (13, 13)
y (13, 1)
batch[1].shape (23, 1)
------
SN Dataset[1]
x (13, 36)
a (13, 13)
y (13, 1)
batch_sn[1].shape (23, 1)
```

**Comment by danielegrattarola** [comment]
Seems to be an issue with your dataset, indeed, but I don't see the problem. 

Can you run the following: 

```py
dataset = SN_Dataset()  # or whatever your dataset is called

def print_shapes(g):
    print('x', g.x.shape)
    print('a', g.a.shape)
    print('y', g.y.shape)

print('GRAPH 0')
print_shapes(dataset[0])

print('GRAPH 1')
print_shapes(dataset[1])

loader = DisjointLoader(dataset, node_level=True, batch_size=2, shuffle=False)
batch = loader.__next__()

print('BATCH')
print('x', batch[0][0].shape)
print('a', batch[0][1].shape)
print('i', batch[0][2].shape)
print('y', batch[1].shape)
``` 

Thanks

**Comment by herman-nside** [comment]
I get the following:

```python
GRAPH 0
x (15, 36)
a (15, 15)
y (15, 1)
GRAPH 1
x (13, 36)
a (13, 13)
y (13, 1)
BATCH
x (28, 36)
a (28, 28)
i (28,)
y (28, 1)
```

To be complete, here is my code and the full output:

```python

import spektral
from dataset_class import GNN_Dataset
from spektral.data.dataset import Dataset
from spektral.layers import GraphSageConv
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from spektral.data import Dataset, Graph
from spektral.data import DisjointLoader
import numpy as np

dataset = GNN_Dataset('/dataset/sn/')

def print_shapes(g):
    print('x', g.x.shape)
    print('a', g.a.shape)
    print('y', g.y.shape)

print('GRAPH 0')
print_shapes(dataset[0])

print('GRAPH 1')
print_shapes(dataset[1])

loader = DisjointLoader(dataset, node_level=True, batch_size=2, shuffle=False)
batch = loader.__next__()

print('BATCH')
print('x', batch[0][0].shape)
print('a', batch[0][1].shape)
print('i', batch[0][2].shape)
print('y', batch[1].shape)

batch_size=128
class SN_GNN(Model):
    def __init__(self):
        super().__init__()
        self.X_in = Input(shape=(13, ),
                     name='X_in')
        self.A_in = Input(shape=(None,),
                     sparse=True,
                     name='A_in')
        self.GraphSage = GraphSageConv(32)
        self.output_layer = Dense(1, activation='softmax')

    def call(self, inputs):
        x, a = inputs[0], inputs[1]
        x = self.GraphSage([x, a])
        out = self.output_layer(x)
        return out

class MyDataset(Dataset):
    def read(self):
        return [
            Graph(x=np.ones((10, 2)), a=np.ones((10, 10)), y=np.ones((10, 1))),
            Graph(x=np.ones((13, 2)), a=np.ones((13, 13)), y=np.ones((13, 1))),
        ]

dataset = MyDataset()


model = SN_GNN()

model.compile(optimizer='Adam', loss='binary_crossentropy')
model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3, batch_size=batch_size)
```
It yields: 
```python
GRAPH 0
x (15, 36)
a (15, 15)
y (15, 1)
GRAPH 1
x (13, 36)
a (13, 13)
y (13, 1)
BATCH
x (28, 36)
a (28, 28)
i (28,)
y (28, 1)
Epoch 1/3
Traceback (most recent call last):
  File "/Users/hca/PycharmProjects/Switching%20notes/ai/tests/test2.py", line 64, in <module>
    model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3, batch_size=batch_size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TypeError: `generator` yielded an element of ((TensorSpec(shape=(24, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([24, 24]), tf.int64), TensorSpec(shape=(24,), dtype=tf.int64, name=None)), TensorSpec(shape=(24, 1), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.int64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(1,), dtype=tf.float64, name=None)) was expected.
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 976, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of ((TensorSpec(shape=(24, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([24, 24]), tf.int64), TensorSpec(shape=(24,), dtype=tf.int64, name=None)), TensorSpec(shape=(24, 1), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 36), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.int64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(1,), dtype=tf.float64, name=None)) was expected.


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_3021]

Function call stack:
train_function
```

**Comment by herman-nside** [comment]
Correction on a previous comment. When I ran the dummy dataset you suggested again, it passes the assert function, but does not train, in fact.

Code:
```python
import spektral
from dataset_class import GNN_Dataset
from spektral.data.dataset import Dataset
from spektral.layers import GraphSageConv
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from spektral.data import Dataset, Graph
from spektral.data import DisjointLoader
import numpy as np

class SN_GNN(Model):
    def __init__(self, n_labels):
        super().__init__()
        self.GraphSage = GraphSageConv(32)
        self.output_layer = Dense(n_labels, activation='softmax')
    def call(self, inputs):
        x, a = inputs[0], inputs[1]
        x = self.GraphSage([x, a])
        out = self.output_layer(x)
        return out

class MyDataset(Dataset):
    def read(self):
        return [
            Graph(x=np.ones((10, 2)), a=np.ones((10, 10)), y=np.ones((10, 1))),
            Graph(x=np.ones((13, 2)), a=np.ones((13, 13)), y=np.ones((13, 1)))
        ]
dataset = MyDataset()
model = SN_GNN(dataset.n_labels)
loader = DisjointLoader(dataset, node_level=True, batch_size=2)
batch = loader.__next__()
assert batch[1].shape == (23, 1)


model.compile(optimizer='Adam', loss='binary_crossentropy')
model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3)
```

Output
```python
Epoch 1/3
Traceback (most recent call last):
  File "/Users/hca/PycharmProjects/Switching%20notes/ai/tests/test.py", line 37, in <module>
    model.fit(loader.load(), steps_per_epoch=loader.steps_per_epoch, epochs=3)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TypeError: `generator` yielded an element of ((TensorSpec(shape=(23, 2), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([23, 23]), tf.float64), TensorSpec(shape=(23,), dtype=tf.int64, name=None)), TensorSpec(shape=(23, 1), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 2), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.float64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(1,), dtype=tf.float64, name=None)) was expected.
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 976, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element of ((TensorSpec(shape=(23, 2), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([23, 23]), tf.float64), TensorSpec(shape=(23,), dtype=tf.int64, name=None)), TensorSpec(shape=(23, 1), dtype=tf.float64, name=None)) where an element of ((TensorSpec(shape=(None, 2), dtype=tf.float64, name=None), SparseTensorSpec(TensorShape([None, None]), tf.float64), TensorSpec(shape=(None,), dtype=tf.int64, name=None)), TensorSpec(shape=(1,), dtype=tf.float64, name=None)) was expected.


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1037]

Function call stack:
train_function
```

**Comment by danielegrattarola** [comment]
Ok so now at least the inputs are correct, the problem is with the model (apparently). 

I have to investigate this, although I suspect it might be a Keras issue. Will keep you posted.

**Comment by danielegrattarola** [comment]
Hi again,

turns out there was a bug in the DisjointLoader in computing the signature of the expected output. 
It's fixed with the last commit on `master` can you install from source and check that it works for you as well?

```sh
git clone git@github.com:danielegrattarola/spektral.git
cd spektral
pip install -U .  # might need sudo if not in a virtual env
```

Thanks

**Comment by herman-nside** [comment]
It works now, thank you very much!
