### ISSUE TITLE
Correct way of making a prediction with Spektral?

### ISSUE THREAD

**Issue by herman-nside** [danielegrattarola/spektral#166]
I am unable to make predictions using a Spektral model that I trained and evaluated using the `model.predict()` using the `loader` functionality. It also takes very long to not make the prediction:

E.g., the following code:

```python
import spektral
from dataset_class import GNN_Dataset
from spektral.data.dataset import Dataset
from spektral.layers import GraphSageConv, EdgeConv, ARMAConv, TAGConv, GCNConv
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from spektral.data import Dataset, Graph
from spektral.data import DisjointLoader
import numpy as np
import tensorflow as tf
from datetime import datetime

t1 = datetime.now()
dataset = GNN_Dataset('/dataset/sn/')
train_val_test_split = [0.8, 0.1, 0.10]
n_samples = len(dataset)
idx_first_val_sample = int(np.floor(n_samples * train_val_test_split[0]))
idx_first_test_sample = int(np.floor(n_samples * (train_val_test_split[0] + train_val_test_split[1])))
dataset_train = dataset[0:idx_first_val_sample]
dataset_val = dataset[idx_first_val_sample: idx_first_test_sample]
dataset_test = dataset[idx_first_test_sample:]

class SN_GNN(Model):
    def __init__(self, n_labels):
        super().__init__()
        self.GraphSage = GraphSageConv(512)
        self.TAGConv = TAGConv(512, K=5)
        self.ARMAConv = ARMAConv(512, order=5)
        self.EdgeConv = EdgeConv(512, mlp_hidden=5)
        self.GCNConv = GCNConv(512)
        self.output_layer = Dense(n_labels, activation='softmax')

    def call(self, inputs):
        x, a = inputs[0], inputs[1]
        x = self.GraphSage([x, a])
        out = self.output_layer(x)
        return out

model = SN_GNN(dataset.n_labels)
loader_train = DisjointLoader(dataset_train, node_level=True, batch_size=128)
loader_val = DisjointLoader(dataset_val, node_level=True, batch_size=1)
loader_test = DisjointLoader(dataset_test, node_level=True, batch_size=1)
t2 = datetime.now()
print(f'Data loaded. Duration: {(t2 - t1).seconds}s')
model.compile(optimizer='Adam', loss='binary_crossentropy')
model.fit(loader_train.load(),
          steps_per_epoch=loader_train.steps_per_epoch,
          epochs=2,
          use_multiprocessing=True)
print(f'Evaluation loss: {model.evaluate(loader_val.load(), steps=loader_val.steps_per_epoch, use_multiprocessing=True)}')
t3 = datetime.now()
print(f'Fit and evaluation complete. Duration: {(t3 - t1).seconds}s')
try:
    model.predict(loader_test.load(), use_multiprocessing=True)
except:
    t4 = datetime.now()
    print(f'Prediction error. Duration: {(t4 - t3).seconds}s')
    pass
```
produces this result:
```python
Data loaded. Duration: 5s
Epoch 1/2
13/13 [==============================] - 2s 27ms/step - loss: 0.6433
Epoch 2/2
13/13 [==============================] - 0s 25ms/step - loss: 0.4864
297/297 [==============================] - 1s 2ms/step - loss: 0.3796
Evaluation loss: 0.3795754015445709
Fit and evaluation complete. Duration: 8s
```
after about an hour of processing - so it never finishes prediction.

However, I can generate a prediction by changing the prediction line to:
```python
for d in dataset_test:
   print(model.predict([d.x, tf.sparse.from_dense(tf.convert_to_tensor(d.a))]))
```

Is there a better way of doing this in Spektral?

**Comment by danielegrattarola** [comment]
HI, 

the default behaviour of loaders is to iterate over the dataset indefinitely (`epochs=None`). 
You can achieve your desired behaviour in two ways:

1. by setting `epochs=1` when instantiating the test loader
2. by setting `steps=loader_test.steps_per_epoch` when calling `predict()`

Cheers

**Comment by herman-nside** [comment]
Doing either of those results in the following error:

```python 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-60f6ffe97ee7>", line 1, in <module>
    model.predict(loader_test, steps=loader_test.steps_per_epoch)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1629, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was float64, but the yielded element was SparseTensor(indices=tf.Tensor(
[[ 0  2]
 [ 1  6]
 [ 1  9]
 [ 1 10]
 [ 2  0]
 [ 2  8]
 [ 3  8]
 [ 4  8]
 [ 4  9]
 [ 5  6]
 [ 6  1]
 [ 6  5]
 [ 6  9]
 [ 7  8]
 [ 8  2]
 [ 8  3]
 [ 8  4]
 [ 8  7]
 [ 9  1]
 [ 9  4]
 [ 9  6]
 [10  1]], shape=(22, 2), dtype=int64), values=tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(22,), dtype=float64), dense_shape=tf.Tensor([11 11], shape=(2,), dtype=int64)).
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 910, in generator_py_func
    script_ops.FuncRegistry._convert(  # pylint: disable=protected-access
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 209, in _convert
    result = np.asarray(value, dtype=dtype, order="C")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'SparseTensor'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 914, in generator_py_func
    six.reraise(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 910, in generator_py_func
    script_ops.FuncRegistry._convert(  # pylint: disable=protected-access
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 209, in _convert
    result = np.asarray(value, dtype=dtype, order="C")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was float64, but the yielded element was SparseTensor(indices=tf.Tensor(
[[ 0  2]
 [ 1  6]
 [ 1  9]
 [ 1 10]
 [ 2  0]
 [ 2  8]
 [ 3  8]
 [ 4  8]
 [ 4  9]
 [ 5  6]
 [ 6  1]
 [ 6  5]
 [ 6  9]
 [ 7  8]
 [ 8  2]
 [ 8  3]
 [ 8  4]
 [ 8  7]
 [ 9  1]
 [ 9  4]
 [ 9  6]
 [10  1]], shape=(22, 2), dtype=int64), values=tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(22,), dtype=float64), dense_shape=tf.Tensor([11 11], shape=(2,), dtype=int64)).
	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_predict_function_11421]
Function call stack:
predict_function
```

I tested the for-loop, and that still works

**Comment by danielegrattarola** [comment]
Does that still happen if you call

```python
model.predict(loader_test.load(), steps=loader_test.steps_per_epoch)
```
?

**Comment by herman-nside** [comment]
No, that works. I thought I tried that, so I'm a bit confused (I restarted the session in the meantime, I'm not sure if that made a difference). But if it works, I'm not going to question it! Sorry for all the questions, and that you for your patience.

**Comment by danielegrattarola** [comment]
Sorry, I forgot to mention that! In your stack trace, I noticed that you were calling 

```py
    model.predict(loader_test, steps=loader_test.steps_per_epoch)
```

> Sorry for all the questions

No problem at all, I need to know if there are usability issues with the library or it will never improve :D
So thanks for opening these issues and feel free to make as many as you like.

**Comment by herman-nside** [comment]
Ah, ok. That makes sense. `loader_test`, and not `loader_test.load()`...
