### ISSUE TITLE
How to modify the GCNconv layer class with a constant tensor to maka sure this custom layer can be saved and loaded

### ISSUE THREAD

**Issue by ambarion** [danielegrattarola/spektral#353]
I really want to know how to fix a constant tensor in the keras model with a GCNconv, a vanilla example can be seen in [the keras issue](https://github.com/keras-team/keras/issues/16275). I faced some deserialize problems when saving and loading a model on the example above. Especially, I need to disable_eager_execution() of keras for some reasons. 

```
img_input = Input(shape=input_shape)

x = Conv2D(51, (3, 3), activation='relu', padding='same', name='conv1_1',
               kernel_regularizer=regularizers.l2(weight_decay))(img_input)
x = Conv2D(51, (3, 3), activation='relu', padding='same', name='conv1_2',
               kernel_regularizer=regularizers.l2(weight_decay))(x)
x = MaxPooling2D((2, 2), strides=(2, 2), name='pool1')(x)

A_numpy = np.eye(51)
A = tf.constant(A_numpy, shape=(51, 51), name='adj_A', dtype=tf.float32)  # I'm not sure I should use constant or variable
A = tf.Variable(A_numpy, shape=(51, 51), name='adj_A', dtype=tf.float32)  

gcn = sp.layers.GCNConv(1024, use_bias=False, kernel_regularizer=regularizers.l2(weight_decay), kernel_initializer='lecun_normal')
x = Reshape((112*112, 51))(x)
x = Permute((2, 1))(x)

gcnoutput = gcn([x, A])

model = Model(inputs=img_input, outputs=gcnoutput1_relu)

with open('model.json', 'w') as f:
    f.write(model.to_json())
```

Save the model will lead to many problem:
when A is a tf.constant, the json will contain a error tensor:
```
...'tensorShape': {'dim': [{'size': '51'}, {'size': '51'}]}, 'tensorContent': 'AACAP95Htjworqk85QKtPPkjpTze...
```
so maybe A should be a tf.Variable.

However, when A is a tf.Variable. Loading the json will lead to another problem.

```
Traceback (most recent call last):
  File "C:\Users\hp-pc\Desktop\ADP-master\src\loadwwww.py", line 21, in <module>
    model = tf.keras.models.model_from_json(loaded_model_json, custom_objects={'GCNConv': GCNConv})
  File "C:\ProgramData\Anaconda3\envs\ADP\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 126, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "C:\ProgramData\Anaconda3\envs\ADP\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\ProgramData\Anaconda3\envs\ADP\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\ProgramData\Anaconda3\envs\ADP\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 668, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "C:\ProgramData\Anaconda3\envs\ADP\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1289, in reconstruct_from_config
    process_node(layer, node_data)
  File "C:\ProgramData\Anaconda3\envs\ADP\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1237, in process_node
    output_tensors = layer(input_tensors, **kwargs)
UnboundLocalError: local variable 'kwargs' referenced before assignment
```

I believe the main problem is that the GCNconv is not designed for the special situation. But I really need your help about how to modify the GCNconv or conv to adapt to this situation. **I just want to design a CNN+GCN, and the GCN always uses a same adjacency matrix A, so I can only use the Keras.fit() to input the image tensor and adj fixed.** PLZ keep the disable_eager_execution(), because enable_eager_execution() also cause some unsolvable problems.

**Comment by danielegrattarola** [comment]
Hi, 

in general, it doesn't seem like a good idea to save the data as part of your model, even if the adjacency matrix stays always the same. 
Could you maybe re-write your model to take the adjacency as input everytime?
