### ISSUE TITLE
Getting Started Tutorial leads to "TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'"

### ISSUE THREAD

**Issue by SophySchubert** [danielegrattarola/spektral#459]
I was following the tutorial but when trying to load the PROTEINS dataset I just got a TypeError. As you can see I created a clean conda-environment 

```bash
(base) sophia@Sophia-PC:~$ conda create --name test
Retrieving notices: ...working... done
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/sophia/miniconda3/envs/test



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) sophia@Sophia-PC:~$ conda activate test
(test) sophia@Sophia-PC:~$ pip install spektral
Defaulting to user installation because normal site-packages is not writeable
Collecting spektral
  Downloading spektral-1.3.1-py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.1/140.1 KB 5.0 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.0-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 KB 6.8 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 10.8 MB/s eta 0:00:00
Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from spektral) (2.0.2)
Collecting networkx
  Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.4 MB/s eta 0:00:00
Collecting lxml
  Downloading lxml-5.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 10.7 MB/s eta 0:00:00
Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 10.8 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 MB 10.4 MB/s eta 0:00:00
Requirement already satisfied: tensorflow>=2.2.0 in ./.local/lib/python3.10/site-packages (from spektral) (2.18.0)
Requirement already satisfied: requests in ./.local/lib/python3.10/site-packages (from spektral) (2.32.3)
Collecting joblib
  Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 KB 8.6 MB/s eta 0:00:00
Requirement already satisfied: grpcio<2.0,>=1.24.3 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (1.67.1)
Requirement already satisfied: h5py>=3.11.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (3.12.1)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow>=2.2.0->spektral) (1.16.0)
Requirement already satisfied: keras>=3.5.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (3.6.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow>=2.2.0->spektral) (59.6.0)
Requirement already satisfied: astunparse>=1.6.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (1.6.3)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (0.6.0)
Requirement already satisfied: opt-einsum>=2.3.2 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (3.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (0.2.0)
Requirement already satisfied: wrapt>=1.11.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (1.16.0)
Requirement already satisfied: absl-py>=1.0.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (2.1.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (5.28.3)
Requirement already satisfied: typing-extensions>=3.6.6 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (4.12.2)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (0.4.1)
Requirement already satisfied: tensorboard<2.19,>=2.18 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (2.18.0)
Requirement already satisfied: packaging in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (24.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (0.37.1)
Requirement already satisfied: flatbuffers>=24.3.25 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (24.3.25)
Requirement already satisfied: libclang>=13.0.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (18.1.1)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.10/site-packages (from tensorflow>=2.2.0->spektral) (2.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.10/site-packages (from requests->spektral) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.10/site-packages (from requests->spektral) (2024.6.2)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.10/site-packages (from requests->spektral) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.10/site-packages (from requests->spektral) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->spektral) (2022.1)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 9.5 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 KB 9.2 MB/s eta 0:00:00
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow>=2.2.0->spektral) (0.37.1)
Requirement already satisfied: optree in ./.local/lib/python3.10/site-packages (from keras>=3.5.0->tensorflow>=2.2.0->spektral) (0.13.0)
Requirement already satisfied: rich in ./.local/lib/python3.10/site-packages (from keras>=3.5.0->tensorflow>=2.2.0->spektral) (13.9.4)
Requirement already satisfied: namex in ./.local/lib/python3.10/site-packages (from keras>=3.5.0->tensorflow>=2.2.0->spektral) (0.0.8)
Requirement already satisfied: werkzeug>=1.0.1 in ./.local/lib/python3.10/site-packages (from tensorboard<2.19,>=2.18->tensorflow>=2.2.0->spektral) (3.0.3)
Requirement already satisfied: markdown>=2.6.8 in ./.local/lib/python3.10/site-packages (from tensorboard<2.19,>=2.18->tensorflow>=2.2.0->spektral) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in ./.local/lib/python3.10/site-packages (from tensorboard<2.19,>=2.18->tensorflow>=2.2.0->spektral) (0.7.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./.local/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow>=2.2.0->spektral) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.local/lib/python3.10/site-packages (from rich->keras>=3.5.0->tensorflow>=2.2.0->spektral) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.local/lib/python3.10/site-packages (from rich->keras>=3.5.0->tensorflow>=2.2.0->spektral) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in ./.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow>=2.2.0->spektral) (0.1.2)
Installing collected packages: tzdata, tqdm, threadpoolctl, scipy, python-dateutil, networkx, lxml, joblib, scikit-learn, pandas, spektral
Successfully installed joblib-1.4.2 lxml-5.3.0 networkx-3.4.2 pandas-2.2.3 python-dateutil-2.9.0.post0 scikit-learn-1.5.2 scipy-1.14.1 spektral-1.3.1 threadpoolctl-3.5.0 tqdm-4.67.0 tzdata-2024.2
(test) sophia@Sophia-PC:~$ python3
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2024-11-13 11:05:37.383894: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-13 11:05:37.496350: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1731492337.541094    1346 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1731492337.555387    1346 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-13 11:05:37.664744: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> import spektral
>>> from spektral.datasets import TUDataset
>>> data = TUDataset("PROTEINS")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sophia/.local/lib/python3.10/site-packages/spektral/datasets/tudataset.py", line 66, in __init__
    super().__init__(**kwargs)
  File "/home/sophia/.local/lib/python3.10/site-packages/spektral/data/dataset.py", line 118, in __init__
    self.graphs = self.read()
  File "/home/sophia/.local/lib/python3.10/site-packages/spektral/datasets/tudataset.py", line 128, in read
    [_normalize(xl_[:, None], "ohe") for xl_ in x_labs.T], -1
  File "/home/sophia/.local/lib/python3.10/site-packages/spektral/datasets/tudataset.py", line 128, in <listcomp>
    [_normalize(xl_[:, None], "ohe") for xl_ in x_labs.T], -1
  File "/home/sophia/.local/lib/python3.10/site-packages/spektral/datasets/tudataset.py", line 219, in _normalize
    fnorm = OneHotEncoder(sparse=False, categories="auto")
TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'
>>>
```

pip freeze gives me following libraries:
```
absl-py==2.1.0
astunparse==1.6.3
Babel==2.8.0
blinker==1.8.2
certifi==2024.6.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
dbus-python==1.2.18
distro==1.7.0
distro-info==1.1+ubuntu0.1
Flask==3.0.3
flatbuffers==24.3.25
gast==0.6.0
google-pasta==0.2.0
grpcio==1.67.1
h5py==3.12.1
httplib2==0.20.2
idna==3.7
importlib-metadata==4.6.4
itsdangerous==2.2.0
jeepney==0.7.1
Jinja2==3.1.4
joblib==1.4.2
keras==3.6.0
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
libclang==18.1.1
lxml==5.3.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
ml-dtypes==0.4.1
more-itertools==8.10.0
namex==0.0.8
netifaces==0.11.0
networkx==3.4.2
numpy==2.0.2
nvidia-cublas-cu12==12.5.3.2
nvidia-cuda-cupti-cu12==12.5.82
nvidia-cuda-nvcc-cu12==12.5.82
nvidia-cuda-nvrtc-cu12==12.5.82
nvidia-cuda-runtime-cu12==12.5.82
nvidia-cudnn-cu12==9.3.0.75
nvidia-cufft-cu12==11.2.3.61
nvidia-curand-cu12==10.3.6.82
nvidia-cusolver-cu12==11.6.3.83
nvidia-cusparse-cu12==12.5.1.3
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.5.82
oauthlib==3.2.0
opt_einsum==3.4.0
optree==0.13.0
packaging==24.2
pandas==2.2.3
protobuf==5.28.3
Pygments==2.18.0
PyGObject==3.42.1
pyinotify==0.9.6
PyJWT==2.3.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
python-apt==2.4.0+ubuntu2
python-dateutil==2.9.0.post0
pytz==2022.1
PyYAML==5.4.1
requests==2.32.3
rich==13.9.4
scikit-learn==1.5.2
scipy==1.14.1
SecretStorage==3.3.1
simplejson==3.17.6
six==1.16.0
spektral==1.3.1
systemd-python==234
tensorboard==2.18.0
tensorboard-data-server==0.7.2
tensorflow==2.18.0
tensorflow-io-gcs-filesystem==0.37.1
termcolor==2.5.0
threadpoolctl==3.5.0
tqdm==4.67.0
typing_extensions==4.12.2
tzdata==2024.2
ubuntu-advantage-tools==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==2.2.2
wadllib==1.3.6
Werkzeug==3.0.3
wrapt==1.16.0
youtube-dl==2021.12.17
zipp==1.0.0
```

**Comment by SophySchubert** [comment]
Sorry, seems to be a problem with python 3.10.12 as it works with version 3.6.12
